### ISSUE TITLE
Is there an "insert at" method?

### ISSUE THREAD

**Issue by MikeiLL** [decodelabs/tagged#5]
Hey, man.

Is there a method to insert an option to a select:

```
    public static function build_filter_select( $filter_name, $label ) {
        return Html::list(
                    self::$schedule[$filter_name],
                    'select#test',
                    'option',
                    function( $list_item, $option, $k ) use ( $filter_name, $label ) {
                        $option->setAttribute( 'value', $k );
                        return $list_item;
                    }
        )->setAttribute( 'name', $filter_name )
        ->setAttribute( 'class', 'day-of-classes' )
        ->setAttribute( 'label', $label )
        //->insertChild( 0, Html::option( $label ) ); // LIKE THIS
    }
```

**Comment by betterthanclay** [comment]
Hi Mike.

At a core level, the answer is yes, however, as it stands, for the example you have above, the answer is unfortunately not.

`Element` instances are collections, so if you have one with lots of items within it, you can do this for example:

```php
// Add new div as 5th element
$element->put(4, Html::div('stuff'));

// Or replace 5th element
$element->set(4, Html::div('replacement'));
```

BUT, right now this doesn't work with `Elements` created with generators as their output is concatenated to a single string while rendering to avoid using lots of memory - the `Element` you get back from `Html::list()` only has one item in the collection, which is a string containing all the raw inner html that goes into it.

I'll need to think it through, but I reckon it should be possible export each individual item from each `yield` statement during rendering of generators so long as each of those items is rendered in-place before being added to the collection - this would give you the solution you're looking for here. 

I'll put it on my todo list and will let you know once it's implemented.

**Comment by MikeiLL** [comment]
@betterthanclay Fantastic.

**Comment by betterthanclay** [comment]
Hi @MikeiLL, I've just rolled out an update to the Elementary package (which Tagged is based on) which implements a new method: `normalize()`

```php
$list = Html::list([1, 2, 3], 'select', 'option', function () {
        return 'value';
    })
    ->normalize()
    ->put(2, Html::option('new'));
```

By calling `normalize()` on any element, any child items that are wrapped in a Generator, Iterable, or Closure get resolved, and added to the body collection as individual array entries.

You can then add, remove and update those entries however you like with `put()`, `set()`, `remove()`, etc.

Just make sure that Elementary gets updated to version 0.2.5 to be able to use this feature.

**Comment by MikeiLL** [comment]
@betterthanclay You are beautiful!
