### ISSUE TITLE
Parse Php data to script tag?

### ISSUE THREAD

**Issue by MikeiLL** [decodelabs/tagged#7]
Hey, @betterthanclay. Continues to be a great tool. We'd like to parse out some Php data to a `<script>`.

Is that already supported? Best to use the `raw` method?

Thanks.

**Comment by MikeiLL** [comment]
This seems to work:

```
yield Html::script(
    new \DecodeLabs\Tagged\Buffer(json_encode( $the_data ))
);
```

**Comment by betterthanclay** [comment]
Hi Mike.

Based on what you've posted, this is a little shorter, plus I've added a type attribute which you may or may not need:

```php
yield Html::script(Html::raw(json_encode( $the_data )), [
    'type' => 'application/json'
]);
```

It's not actually parsing anything, just spitting out the json data in a script tag, but it seems like this will do what you need..
